Mirana:
  name: Mirana
  pos:
    one: true
    two: true
    three: true
    four: false
    five: false
  pick:
    one: true
    two: true
    three: true
    four: true
    five: true
  ban:
    first_phase: false
    second_phase: true
    third_phase: true
